Repository datachecks/dcs-core, pull requests merged in 2023-09, with the labels that each got.

#72 feat(metric): implemented null count calculation
  datachecks/core/common/models/metric.py
  datachecks/core/datasource/search_datasource.py
  datachecks/core/datasource/sql_datasource.py
  datachecks/core/metric/manager.py
  datachecks/core/metric/numeric_metric.py
  tests/core/metric/test_metric_manager.py
  tests/core/metric/test_numeric_metric.py
  tests/integration/datasource/test_search_datasource.py
  tests/integration/datasource/test_sql_datasource.py
Labels: ⚡️enhancement, metric

#73 docs: update website-docs
  docs/index.md
  docs/metrics/combined.md
  docs/metrics/completeness.md
  docs/metrics/numeric_distribution.md
  docs/metrics/uniqueness.md
Labels: 📜 documentation

#67 feat(metrics): implemented distinct count with tests
  datachecks/core/datasource/search_datasource.py
  datachecks/core/datasource/sql_datasource.py
  datachecks/core/metric/manager.py
  datachecks/core/metric/numeric_metric.py
  tests/core/metric/test_metric_manager.py
  tests/core/metric/test_numeric_metric.py
  tests/integration/datasource/test_search_datasource.py
  tests/integration/datasource/test_sql_datasource.py
Labels: ⚡️enhancement

#78 feat(metrics): added empty-string-count and tests
  datachecks/core/common/models/metric.py
  datachecks/core/datasource/search_datasource.py
  datachecks/core/datasource/sql_datasource.py
  datachecks/core/metric/manager.py
  datachecks/core/metric/numeric_metric.py
  tests/core/metric/test_metric_manager.py
  tests/core/metric/test_numeric_metric.py
  tests/integration/datasource/test_search_datasource.py
  tests/integration/datasource/test_sql_datasource.py
Labels: metric

#85 feat(metrics): implemented empty-string-percentage metric and tests
  datachecks/core/common/models/metric.py
  datachecks/core/datasource/search_datasource.py
  datachecks/core/datasource/sql_datasource.py
  datachecks/core/metric/manager.py
  datachecks/core/metric/numeric_metric.py
  tests/core/metric/test_metric_manager.py
  tests/core/metric/test_numeric_metric.py
  tests/integration/datasource/test_search_datasource.py
  tests/integration/datasource/test_sql_datasource.py
Labels: metric

#87 fix(datasource): included qualified_table_name to all table calls
  datachecks/core/datasource/sql_datasource.py
Labels: 🐞 bug, metric

#97 fix(metrics): round function in average and variance metric
  datachecks/core/datasource/sql_datasource.py
  tests/integration/test_databases_availability.py
Labels: 🐞 bug

#96 fix(metric): field_name not being accepted in open-search and elastic-search in freshness metric
  datachecks/core/configuration/configuration_parser.py
Labels: 🐞 bug

#108 feat(metrics): implemented standard deviation + tests
  datachecks/core/datasource/search_datasource.py
  datachecks/core/datasource/sql_datasource.py
  datachecks/core/metric/manager.py
  datachecks/core/metric/numeric_metric.py
  docs/configuration/metric_configuration.md
  docs/metrics/numeric_distribution.md
  tests/core/metric/test_metric_manager.py
  tests/core/metric/test_numeric_metric.py
  tests/integration/datasource/test_elasticsearch_datasource.py
  tests/integration/datasource/test_search_datasource.py
  tests/integration/datasource/test_sql_datasource.py
Labels: metric
