Repository datachecks/dcs-core, pull requests merged in 2025-06, with the labels that each got.

#309 feat: database version query
  dcs_core/core/datasource/sql_datasource.py
  dcs_core/integrations/databases/oracle.py
  dcs_core/integrations/databases/postgres.py
Labels: Review effort 2/5

#307 chore: version bump 0.8.7
  dcs_core/__version__.py
  pyproject.toml
Labels: Review effort 1/5

#310 feat: fetch rows with column name
  dcs_core/integrations/databases/mssql.py
  dcs_core/integrations/databases/mysql.py
  dcs_core/integrations/databases/oracle.py
  dcs_core/integrations/databases/postgres.py
  dcs_core/integrations/databases/sybase.py
Labels: Review effort 3/5
